# Generated by Django 2.2.1 on 2019-12-09 15:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('simple_email_confirmation', '0001_initial'),
        ('tracking', '0002_auto_20180918_2014'),
        ('admin', '0003_logentry_add_action_flag_choices'),
        ('user_management', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
