"""
Django settings for analytica project.

Generated by 'django-admin startproject' using Django 2.1.7.

For more information on this file, see
https://docs.djangoproject.com/en/2.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/2.1/ref/settings/
"""

import os
from decouple import config


# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

CORE_FILE_PATH = os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__)))) + "/wherehouse"


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/2.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = '7j^1)vjx8$9jqr_i9^_8_b6w2&%g&nf_sb6)%5eqy)p9!r+6g5'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True
ALLOWED_HOSTS = ['*']


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'tracking',
    'home',
    'user_management',
    'simple_email_confirmation',
    'admin_panel',
    'crispy_forms',
    'widget_tweaks',
    'rolepermissions',
    'data_analyzer',
    'survey',

    'rest_framework',
    'rest_framework.authtoken',
    'chartGenerate',
    'dataframe',
    'client',
    # 'menu',
]

# SIMPLE_EMAIL_CONFIRMATION_EMAIL_ADDRESS_MODEL = 'simple_email_confirmation.EmailAddress'


REST_FRAMEWORK = {
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.PageNumberPagination',
    'PAGE_SIZE': 2
}

TRACK_AJAX_REQUESTS = True
TRACK_PAGEVIEWS = True
TRACK_IGNORE_STATUS_CODES = [400, 404, 403, 405, 410, 500]
TRACK_REFERER = True
TRACK_QUERY_STRING = True
TRACK_SUPERUSERS = False


MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'tracking.middleware.VisitorTrackingMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'compression_middleware.middleware.CompressionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'analytica.middleware.LoginRequiredMiddleware',
]

ROOT_URLCONF = 'analytica.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'home.context_processors.app_versions',
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'django.template.context_processors.media',
            ],
        },
    },
]

WSGI_APPLICATION = 'analytica.wsgi.application'


# Database
# https://docs.djangoproject.com/en/2.1/ref/settings/#databases

# DATABASES = {
#     'default': {
#         'ENGINE': 'django.db.backends.sqlite3',
#         'NAME': os.path.join(BASE_DIR, 'db.sqlite3'),
#     }
# }

DATABASES = {
    # 'default': {
    #     'ENGINE': 'django.db.backends.mysql',
    #     'OPTIONS': {
    #         'sql_mode': 'traditional',
    #     },
    #     'NAME': config('DB_NAME'),
    #     'USER': config('DB_USER'),
    #     'PASSWORD': config('DB_PASSWORD'),
    #     'HOST': config('HOST'),  # Or an IP Address that your DB is hosted on
    #     'PORT': config('PORT'),
    # }

    'default': 
    {
        #'ENGINE': 'django.db.backends.postgresql',
        'ENGINE': 'django.db.backends.postgresql_psycopg2',
        'NAME': config('DB_NAME'),                     
        'USER': config('DB_USER'),
        'PASSWORD': config('DB_PASSWORD'),
        'HOST': config('HOST'),
        'PORT': config('PORT'),
    }
}


# Redis Connection
# CACHES = {
#     "default": {
#         "BACKEND": "django_redis.cache.RedisCache",
#         "LOCATION": "redis://127.0.0.1:6379/2",
#         "OPTIONS": {
#             "CLIENT_CLASS": "django_redis.client.DefaultClient",
#              "COMPRESSOR": "django_redis.compressors.zlib.ZlibCompressor",
#         }
#     }
# }

# SESSION_ENGINE = "django.contrib.sessions.backends.cache"
# SESSION_CACHE_ALIAS = "default"

# Password validation
# https://docs.djangoproject.com/en/2.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


VERSION = "3.5"

# Internationalization
# https://docs.djangoproject.com/en/2.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'Asia/Kolkata'
USE_I18N = True
USE_L10N = True
USE_TZ = False

ROLEPERMISSIONS_MODULE = 'analytica.roles'

STATIC_URL = '/static/'
STATIC_ROOT = os.path.join(BASE_DIR, "static")

# APPEND_SLASH = False

# This folder contains all the dataframe source
# DATA_FRAME_SOURCE = os.path.join(BASE_DIR, "static", "data_frame_source")

# STATICFILES_DIRS = (os.path.join(BASE_DIR, "sfiles"), )ssss

MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

CRISPY_TEMPLATE_PACK = 'bootstrap4'

TEMPLATE_DIRS = (os.path.join(BASE_DIR, 'templates'),)
TEMPLATE_LOADERS = ('django.template.loaders.filesystem.Loader','django.template.loaders.app_directories.Loader',)


LOGIN_EXEMPT_URLS = [
    r'^$',
    r'^login/$',
    r'^signup/$',
    r'^bcpm_login/$',
    r'^about/$',
    r'^contact/$',
    r'^search/$',
    r'^notices/$',
    r'^discussions/$',
    r'^bills_acts/$',
    r'^core_admin/$',
    r'^account/login/$',
    r'^account/logout/$',
    r'^accounts/password_reset/$',
    r'^accounts/password_reset/done/$',
    r'^accounts/reset/*',
    r'^api-token-auth/$'
]

DATA_UPLOAD_MAX_NUMBER_FIELDS = 10240

LOGIN_URL = '/'
# LOGIN_REDIRECT_URL = '/admin/analytics/asha'
LOGOUT_REDIRECT_URL = LOGIN_URL

# Email Settings
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_USE_TLS = True
EMAIL_HOST = 'smtp.gmail.com'
EMAIL_HOST_USER = 'aarongoldstein532@gmail.com'
EMAIL_HOST_PASSWORD = 'givefive5gmail'
EMAIL_PORT = 587

# session expire
SESSION_EXPIRE_AT_BROWSER_CLOSE = True
SESSION_COOKIE_AGE = 4500 #
SESSION_SAVE_EVERY_REQUEST = True


