# Generated by Django 2.2.1 on 2019-12-21 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0002_frame_edit_request'),
    ]

    operations = [
        migrations.AddField(
            model_name='frame_edit_request',
            name='comment',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='frame_edit_request',
            name='verified',
            field=models.BooleanField(default=False),
        ),
    ]
