# Generated by Django 2.2.1 on 2019-12-23 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0003_auto_20191221_1236'),
    ]

    operations = [
        migrations.AlterField(
            model_name='frame_edit_request',
            name='verified',
            field=models.NullBooleanField(),
        ),
    ]
