# Generated by Django 3.0.3 on 2020-04-06 11:28

from django.conf import settings
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('admin_panel', '0004_auto_20191223_1257'),
    ]

    operations = [
        migrations.AddField(
            model_name='dataframe',
            name='meta',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dataframe',
            name='path',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='dataframe',
            name='rows',
            field=models.IntegerField(default=-1),
        ),
        migrations.AddField(
            model_name='dataframe',
            name='schema_hash',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='dataframe',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='dataframe',
            name='name',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
