# Generated by Django 3.0.3 on 2020-04-16 12:01

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0005_auto_20200406_1128'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chartconfig',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('conf', django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True)),
                ('about', models.TextField(blank=True, null=True)),
                ('frame', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='admin_panel.Dataframe')),
            ],
        ),
    ]
