# Generated by Django 3.0.3 on 2020-04-20 16:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0006_chartconfig'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Chartconfig',
        ),
    ]
