# Generated by Django 3.0.3 on 2020-04-23 11:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chartGenerate', '0002_auto_20200423_1124'),
        ('admin_panel', '0007_delete_chartconfig'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='frame_edit_request',
            name='user',
        ),
        migrations.DeleteModel(
            name='Dataframe',
        ),
        migrations.DeleteModel(
            name='Frame_edit_request',
        ),
    ]
