# Generated by Django 2.2.1 on 2019-09-21 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0002_auto_20190904_1740'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answers',
            name='indicator',
        ),
        migrations.AlterField(
            model_name='geography',
            name='census_code',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='geography',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='geography',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
