# Generated by Django 2.2.1 on 2019-09-21 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0003_auto_20190921_0958'),
    ]

    operations = [
        migrations.AlterField(
            model_name='geography',
            name='name',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='geographylevel',
            name='name',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
