# Generated by Django 2.2.1 on 2019-09-21 16:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0006_auto_20190921_1634'),
    ]

    operations = [
        migrations.AlterField(
            model_name='indicatorsurveygeo',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='survey.Category'),
        ),
    ]
