# Generated by Django 2.2.1 on 2019-09-21 17:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0007_auto_20190921_1638'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answers',
            name='attribute',
        ),
        migrations.RemoveField(
            model_name='attribute',
            name='indicatorsurveygeo',
        ),
        migrations.CreateModel(
            name='Attrindicatorsurveygeo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('attribute', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='survey.Attribute')),
                ('indicatorsurveygeo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='survey.Indicatorsurveygeo')),
            ],
        ),
        migrations.AddField(
            model_name='answers',
            name='attrindicatorsurveygeo',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='survey.Attrindicatorsurveygeo'),
            preserve_default=False,
        ),
    ]
