# Generated by Django 2.2.1 on 2019-09-21 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0008_auto_20190921_1733'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answers',
            name='value',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
