# Generated by Django 2.2.1 on 2019-09-23 11:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0009_auto_20190921_1856'),
    ]

    operations = [
        migrations.CreateModel(
            name='AttributeToIndicatorToSurveyToGeography',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='IndicatorToSurveyToGeography',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='indicatorsurveygeo',
            name='category',
        ),
        migrations.RemoveField(
            model_name='indicatorsurveygeo',
            name='indicator',
        ),
        migrations.RemoveField(
            model_name='indicatorsurveygeo',
            name='surveygeo',
        ),
        migrations.RemoveField(
            model_name='answers',
            name='attrindicatorsurveygeo',
        ),
        migrations.RenameModel(
            old_name='Surveygeo',
            new_name='SurveyToGeography',
        ),
        migrations.DeleteModel(
            name='Attrindicatorsurveygeo',
        ),
        migrations.DeleteModel(
            name='Indicatorsurveygeo',
        ),
        migrations.AddField(
            model_name='indicatortosurveytogeography',
            name='SurveyToGeography',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='survey.SurveyToGeography'),
        ),
        migrations.AddField(
            model_name='indicatortosurveytogeography',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='survey.Category'),
        ),
        migrations.AddField(
            model_name='indicatortosurveytogeography',
            name='indicator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='survey.Indicator'),
        ),
        migrations.AddField(
            model_name='attributetoindicatortosurveytogeography',
            name='IndicatorToSurveyToGeography',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='survey.IndicatorToSurveyToGeography'),
        ),
        migrations.AddField(
            model_name='attributetoindicatortosurveytogeography',
            name='attribute',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='survey.Attribute'),
        ),
        migrations.AddField(
            model_name='answers',
            name='AttributeToIndicatorToSurveyToGeography',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='survey.AttributeToIndicatorToSurveyToGeography'),
            preserve_default=False,
        ),
    ]
