# Generated by Django 2.2.1 on 2019-09-23 12:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0012_auto_20190923_1202'),
    ]

    operations = [
        migrations.RenameField(
            model_name='geography',
            old_name='related_to',
            new_name='Geography',
        ),
    ]
