# Generated by Django 2.2.1 on 2019-09-23 12:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0013_auto_20190923_1208'),
    ]

    operations = [
        migrations.RenameField(
            model_name='indicatortosurveytogeography',
            old_name='category',
            new_name='Category',
        ),
        migrations.RenameField(
            model_name='indicatortosurveytogeography',
            old_name='indicator',
            new_name='Indicator',
        ),
    ]
