# Generated by Django 2.2.1 on 2019-09-23 12:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0014_auto_20190923_1209'),
    ]

    operations = [
        migrations.RenameField(
            model_name='attributetoindicatortosurveytogeography',
            old_name='attribute',
            new_name='Attribute',
        ),
    ]
